SRCS += \
	$(KEYBOARD_DIR)/usbmaster.c \

APP_DEFS += -DABELX
MCU = STM32L072
CUSTOM_MATRIX = yes
TINYUSB_ENABLE = yes
TINYUSB_USE_HAL = yes
#VIAL_ENABLE = no 
ACTIONMAP_ENABLE = yes

LINKER_PATH = $(KEYBOARD_DIR)
